(asdf:defsystem "cl-parser-kit-test"
  :description "Tests for cl-parser-kit."
  :version "0.1.0"
  :author "takeokunn"
  :license "MIT"
  :homepage "https://github.com/takeokunn/cl-parser-kit"
  :bug-tracker "https://github.com/takeokunn/cl-parser-kit/issues"
  :source-control (:git "https://github.com/takeokunn/cl-parser-kit.git")
  :depends-on ("cl-parser-kit" "cl-weave" "cl-prolog/weave")
  :pathname "t"
  :serial t
  :components ((:file "package")
               (:file "tokens-test")
               (:file "tokenizer-support")
               (:file "tokenizer-fixtures")
               (:file "tokenizer-basic-test")
               (:file "tokenizer-span-test")
               (:file "tokenizer-comment-test")
               (:file "tokenizer-string-test")
               (:file "tokenizer-comment-rules-test")
               (:file "tokenizer-keyword-test")
               (:file "tokenizer-identifier-test")
               (:file "tokenizer-char-rule-test")
               (:file "tokenizer-rules-extra-test")
               (:file "spans-test")
               (:file "diagnostics-test")
               (:file "mutation-testing-test")
                (:file "combinators-support")
                (:file "combinators-fixtures")
                (:file "combinators-core-test")
               (:file "combinators-chain-test")
               (:file "combinators-separator-test")
               (:file "combinators-delimited-test")
               (:file "combinators-control-test")
               (:file "combinators-transform-test")
               (:file "combinators-choice-test")
               (:file "combinators-repeat-test")
               (:file "combinators-apply-test")
               (:file "combinators-macros-test")
               (:file "combinators-token-test")
               (:file "combinators-recover-test")
               (:file "combinators-backtrack-test")
               (:file "combinators-permutation-test")
               (:file "combinators-expression-test")
               (:file "combinators-memoize-test")
               (:file "pratt-support")
               (:file "pratt-fixtures")
               (:file "pratt-basic-test")
               (:file "pratt-failure-trailing-test")
               (:file "pratt-failure-test")
               (:file "pratt-source-test")
               (:file "pratt-contract-test")
               (:file "pratt-builders-test")
               (:file "prolog-contract-test")
               (:file "parser-support")
               (:file "parser-core-test")
               (:file "parser-diagnostic-test")
               (:file "parser-runtime-test")
               (:file "parser-contract-test")
               (:file "parser-properties-test")
               (:file "examples-doc-data")
               (:file "examples-common-support")
               (:file "examples-doc-support")
               (:file "examples-file-support")
               (:file "examples-runtime-support")
               (:file "examples-docs-test")
               (:file "examples-snippets-core-test")
               (:file "examples-snippets-core-advanced-test")
               (:file "examples-snippets-structures-test")
               (:file "examples-snippets-runtime-test")
               (:file "examples-advanced-snippets-test")
               (:file "examples-files-test")
               (:file "examples-ops-test")
               (:file "trees-test")
               (:file "trees-traversal-test"))
  :perform (asdf:test-op (op system)
             (declare (ignore op system))
             (unless (uiop:symbol-call :cl-weave
                                       :run-all
                                       :reporter :spec
                                       :pass-with-no-tests nil)
               (error "cl-parser-kit tests failed"))))
