(in-package :cl-parser-kit/test)

(it-sequential "combinator-seq-test"
  (with-combinator-tokens (tokens *identifier-plus-number-token-specs*)
    (let ((parser (seq (type-token :identifier)
                       (type-token :plus)
                       (type-token :number))))
      (assert-combinator-values (parse-tokens parser tokens)
          (ok value next failure)
        (declare (ignore failure))
        (expect ok :to-be-truthy)
        (expect next :to-equal 3)
        (expect (token-type (first value)) :to-equal :identifier)))))

(it-sequential "combinator-canonical-surface-test"
  (with-combinator-tokens (tokens *identifier-plus-number-token-specs*)
    (let ((seq-parser (seq (type-token :identifier)
                           (type-token :plus)))
          (alt-parser (alt (type-token :number)
                           (type-token :identifier)))
          (opt-parser (opt (type-token :identifier))))
      (assert-combinator-values (parse-tokens seq-parser tokens)
          (ok value next failure)
        (declare (ignore failure))
        (expect ok :to-be-truthy)
        (expect next :to-equal 2)
        (expect (length value) :to-equal 2))
      (assert-combinator-values (parse-tokens alt-parser tokens)
          (ok value next failure)
        (declare (ignore failure))
        (expect ok :to-be-truthy)
        (expect next :to-equal 1)
        (expect (token-type value) :to-equal :identifier))
      (assert-combinator-values (parse-tokens opt-parser #())
          (ok value next failure)
        (declare (ignore failure))
        (expect ok :to-be-truthy)
        (expect value :to-be-falsy)
        (expect next :to-equal 0)))))

(it-sequential "combinator-qualified-public-surface-test"
  (with-combinator-tokens (tokens *identifier-comma-number-token-specs*)
    (let ((parser (cl-parser-kit:seq
                   (cl-parser-kit:alt
                    (cl-parser-kit:type-token :identifier)
                    (cl-parser-kit:type-token :number))
                   (cl-parser-kit:opt
                    (cl-parser-kit:type-token :comma))
                   (cl-parser-kit:type-token :number))))
      (assert-combinator-values (parse-tokens parser tokens)
          (ok value next failure)
        (declare (ignore failure))
        (expect ok :to-be-truthy)
        (expect next :to-equal 3)
        (expect (token-type (first value)) :to-equal :identifier)
        (expect (token-type (second value)) :to-equal :comma)
        (expect (token-type (third value)) :to-equal :number)))))

(it-sequential "combinator-alt-with-no-branches-fails-cleanly-test"
  (assert-combinator-values (parse-tokens (alt) #())
      (ok value next failure)
    (expect ok :to-be-falsy)
    (expect value :to-be-falsy)
    (expect next :to-equal 0)
    (expect (parse-failure-position failure) :to-equal 0)
    (expect (parse-failure-expected failure) :to-equal :alternative)
    (expect (parse-failure-actual failure) :to-be-falsy)))

(it-sequential "combinator-many-test"
  (with-combinator-tokens
      (tokens '((:type :identifier :text "foo")
                (:type :identifier :text "bar")
                (:type :plus :text "+")))
    (let ((parser (many (type-token :identifier))))
      (assert-combinator-values (parse-tokens parser tokens)
          (ok value next failure)
        (declare (ignore failure))
        (expect ok :to-be-truthy)
        (expect next :to-equal 2)
        (expect (length value) :to-equal 2)
        (expect (token-type (first value)) :to-equal :identifier)
        (expect (token-type (second value)) :to-equal :identifier)))))

(it-sequential "combinator-many-rejects-non-advancing-parser-test"
  (let ((parser (many (return-parser :ok))))
    (assert-combinator-values (parse-tokens parser #())
        (ok value next failure)
      (expect ok :to-be-falsy)
      (expect value :to-be-falsy)
      (expect next :to-equal 0)
      (expect (parse-failure-expected failure) :to-equal :progressing-parser)
      (expect (parser-name (parse-failure-actual failure)) :to-equal :return))))

(it-sequential "combinator-many-propagates-progressed-failure-test"
  (let* ((tokens (vector (make-token :type :plus :text "+")))
         (parser (many (seq (type-token :plus)
                            (type-token :number)))))
    (assert-combinator-failure (parse-tokens parser tokens)
        (value next failure)
      (expect next :to-equal 1)
      (expect (parse-failure-position failure) :to-equal 1)
      (expect (parse-failure-expected failure) :to-equal :number)
      (expect (parse-failure-actual failure) :to-equal :eof))))

(it-sequential "combinator-many-preserves-recoverable-diagnostics-test"
  (let* ((tokens (vector (make-token :type :identifier :text "foo" :start 0 :end 3)
                         (make-token :type :comma :text "," :start 3 :end 4)))
         (parser (many (lookahead (seq (type-token :identifier)
                                       (end-of-input))))))
    (assert-combinator-success (run-parser parser tokens 0)
        (value next diagnostics)
      (expect value :to-equal '())
      (expect next :to-equal 0)
      (%assert-rendered-diagnostic-contains (first diagnostics)
                                            "Unexpected trailing token"
                                            "1:4-1:5"))))

(it-sequential "combinator-seq-preserves-success-diagnostics-test"
  (let* ((tokens (vector (make-token :type :identifier :text "foo" :start 0 :end 3)
                         (make-token :type :semicolon :text ";" :start 3 :end 4)))
         (parser (seq (opt (lookahead (seq (type-token :identifier)
                                           (end-of-input))))
                      (type-token :identifier))))
    (assert-combinator-success (run-parser parser tokens 0)
        (value next diagnostics)
      (expect (length value) :to-equal 2)
      (expect next :to-equal 1)
      (%assert-rendered-diagnostic-contains (first diagnostics)
                                            "Unexpected trailing token"
                                            "1:4-1:5"))))

(it-sequential "merge-diagnostics-rejects-circular-success-diagnostic-list-test"
  (let ((*maximum-parse-failure-diagnostic-count* 1)
        (diagnostics (list (note-diagnostic "one"))))
    (setf (cdr diagnostics) diagnostics)
    (expect (lambda ()
              (cl-parser-kit::%merge-diagnostics diagnostics))
            :to-throw 'parse-failure-resource-limit-exceeded)))

(it-sequential "merge-diagnostics-rejects-improper-success-diagnostic-list-test"
  (let ((diagnostics (cons (note-diagnostic "one") :tail)))
    (expect (lambda ()
              (cl-parser-kit::%merge-diagnostics diagnostics))
            :to-throw 'parse-failure-resource-limit-exceeded)))

(it-sequential "merge-diagnostics-enforces-aggregate-success-diagnostic-limit-test"
  (let ((*maximum-parse-failure-diagnostic-count* 1))
    (expect (lambda ()
              (cl-parser-kit::%merge-diagnostics
               (list (note-diagnostic "one"))
               (list (note-diagnostic "two"))))
            :to-throw 'parse-failure-resource-limit-exceeded)))

(it-sequential "combinator-many1-test"
  (with-combinator-tokens (tokens '((:type :identifier :text "foo")
                                    (:type :identifier :text "bar")))
    (let ((parser (many1 (type-token :identifier))))
      (assert-combinator-values (parse-tokens parser tokens)
          (ok value next failure)
        (declare (ignore failure))
        (expect ok :to-be-truthy)
        (expect next :to-equal 2)
        (expect (length value) :to-equal 2))))
  (let ((parser (many1 (type-token :identifier))))
    (assert-combinator-values (parse-tokens parser #())
        (ok value next failure)
      (expect ok :to-be-falsy)
      (expect value :to-be-falsy)
      (expect next :to-equal 0)
      (expect (parse-failure-expected failure) :to-equal :identifier))))

(it-sequential "parser-public-accessor-contract-test"
  (let* ((parser (make-parser
                  :name :public-contract
                  :fn (lambda (_input position)
                        (declare (ignore _input))
                        (values t :ok (1+ position) nil)))))
    (expect (typep parser 'parser) :to-be-truthy)
    (expect (parser-name parser) :to-equal :public-contract)
    (expect (functionp (parser-fn parser)) :to-be-truthy)
    (assert-combinator-success (funcall (parser-fn parser) #() 2)
        (value next diagnostics)
      (expect value :to-equal :ok)
      (expect next :to-equal 3)
      (expect diagnostics :to-be-falsy))
    (assert-combinator-success (run-parser parser #() 4)
        (value next diagnostics)
      (expect value :to-equal :ok)
      (expect next :to-equal 5)
      (expect diagnostics :to-be-falsy))))
