(in-package :cl-parser-kit/test)

(deftest-case combinator-seq-test
  (with-combinator-tokens (tokens *identifier-plus-number-token-specs*)
    (let ((parser (seq (type-token :identifier)
                       (type-token :plus)
                       (type-token :number))))
      (assert-combinator-values (parse-tokens parser tokens)
          (ok value next failure)
        (declare (ignore failure))
        (assert-true ok)
        (assert-equal 3 next)
        (assert-equal :identifier (token-type (first value)))))))

(deftest-case combinator-canonical-surface-test
  (with-combinator-tokens (tokens *identifier-plus-number-token-specs*)
    (let ((seq-parser (seq (type-token :identifier)
                           (type-token :plus)))
          (alt-parser (alt (type-token :number)
                           (type-token :identifier)))
          (opt-parser (opt (type-token :identifier))))
      (assert-combinator-values (parse-tokens seq-parser tokens)
          (ok value next failure)
        (declare (ignore failure))
        (assert-true ok)
        (assert-equal 2 next)
        (assert-equal 2 (length value)))
      (assert-combinator-values (parse-tokens alt-parser tokens)
          (ok value next failure)
        (declare (ignore failure))
        (assert-true ok)
        (assert-equal 1 next)
        (assert-equal :identifier (token-type value)))
      (assert-combinator-values (parse-tokens opt-parser #())
          (ok value next failure)
        (declare (ignore failure))
        (assert-true ok)
        (assert-false value)
        (assert-equal 0 next)))))

(deftest-case combinator-qualified-public-surface-test
  (with-combinator-tokens (tokens *identifier-comma-number-token-specs*)
    (let ((parser (cl-parser-kit:seq
                   (cl-parser-kit:alt
                    (cl-parser-kit:type-token :identifier)
                    (cl-parser-kit:type-token :number))
                   (cl-parser-kit:opt
                    (cl-parser-kit:type-token :comma))
                   (cl-parser-kit:type-token :number))))
      (assert-combinator-values (parse-tokens parser tokens)
          (ok value next failure)
        (declare (ignore failure))
        (assert-true ok)
        (assert-equal 3 next)
        (assert-equal :identifier (token-type (first value)))
        (assert-equal :comma (token-type (second value)))
        (assert-equal :number (token-type (third value)))))))

(deftest-case combinator-alt-with-no-branches-fails-cleanly-test
  (assert-combinator-values (parse-tokens (alt) #())
      (ok value next failure)
    (assert-false ok)
    (assert-false value)
    (assert-equal 0 next)
    (assert-equal 0 (parse-failure-position failure))
    (assert-equal :alternative (parse-failure-expected failure))
    (assert-false (parse-failure-actual failure))))

(deftest-case combinator-many-test
  (with-combinator-tokens
      (tokens '((:type :identifier :text "foo")
                (:type :identifier :text "bar")
                (:type :plus :text "+")))
    (let ((parser (many (type-token :identifier))))
      (assert-combinator-values (parse-tokens parser tokens)
          (ok value next failure)
        (declare (ignore failure))
        (assert-true ok)
        (assert-equal 2 next)
        (assert-equal 2 (length value))
        (assert-equal :identifier (token-type (first value)))
        (assert-equal :identifier (token-type (second value)))))))

(deftest-case combinator-many-rejects-non-advancing-parser-test
  (let ((parser (many (return-parser :ok))))
    (assert-combinator-values (parse-tokens parser #())
        (ok value next failure)
      (assert-false ok)
      (assert-false value)
      (assert-equal 0 next)
      (assert-equal :progressing-parser (parse-failure-expected failure))
      (assert-equal :return (parser-name (parse-failure-actual failure))))))

(deftest-case combinator-many-propagates-progressed-failure-test
  (let* ((tokens (vector (make-token :type :plus :text "+")))
         (parser (many (seq (type-token :plus)
                            (type-token :number)))))
    (multiple-value-bind (ok value next failure)
        (parse-tokens parser tokens)
      (assert-false ok)
      (assert-false value)
      (assert-equal 1 next)
      (assert-equal 1 (parse-failure-position failure))
      (assert-equal :number (parse-failure-expected failure))
      (assert-equal :eof (parse-failure-actual failure)))))

(deftest-case combinator-many-preserves-recoverable-diagnostics-test
  (let* ((tokens (vector (make-token :type :identifier :text "foo" :start 0 :end 3)
                         (make-token :type :comma :text "," :start 3 :end 4)))
         (parser (many (lookahead (seq (type-token :identifier)
                                       (end-of-input))))))
    (multiple-value-bind (ok value next diagnostics)
        (run-parser parser tokens 0)
      (assert-true ok)
      (assert-equal '() value)
      (assert-equal 0 next)
      (%assert-rendered-diagnostic-contains (first diagnostics)
                                            "Unexpected trailing token"
                                            "1:4-1:5"))))

(deftest-case combinator-seq-preserves-success-diagnostics-test
  (let* ((tokens (vector (make-token :type :identifier :text "foo" :start 0 :end 3)
                         (make-token :type :semicolon :text ";" :start 3 :end 4)))
         (parser (seq (opt (lookahead (seq (type-token :identifier)
                                           (end-of-input))))
                      (type-token :identifier))))
    (multiple-value-bind (ok value next diagnostics)
        (run-parser parser tokens 0)
      (assert-true ok)
      (assert-equal 2 (length value))
      (assert-equal 1 next)
      (%assert-rendered-diagnostic-contains (first diagnostics)
                                            "Unexpected trailing token"
                                            "1:4-1:5"))))

(deftest-case combinator-many1-test
  (with-combinator-tokens (tokens '((:type :identifier :text "foo")
                                    (:type :identifier :text "bar")))
    (let ((parser (many1 (type-token :identifier))))
      (assert-combinator-values (parse-tokens parser tokens)
          (ok value next failure)
        (declare (ignore failure))
        (assert-true ok)
        (assert-equal 2 next)
        (assert-equal 2 (length value)))))
  (let ((parser (many1 (type-token :identifier))))
    (assert-combinator-values (parse-tokens parser #())
        (ok value next failure)
      (assert-false ok)
      (assert-false value)
      (assert-equal 0 next)
      (assert-equal :identifier (parse-failure-expected failure)))))

(deftest-case parser-public-accessor-contract-test
  (let* ((parser (make-parser
                  :name :public-contract
                  :fn (lambda (_input position)
                        (declare (ignore _input))
                        (values t :ok (1+ position) nil)))))
    (assert-true (typep parser 'parser))
    (assert-equal :public-contract (parser-name parser))
    (assert-true (functionp (parser-fn parser)))
    (multiple-value-bind (ok value next diagnostics)
        (funcall (parser-fn parser) #() 2)
      (assert-true ok)
      (assert-equal :ok value)
      (assert-equal 3 next)
      (assert-false diagnostics))
    (multiple-value-bind (ok value next diagnostics)
        (run-parser parser #() 4)
      (assert-true ok)
      (assert-equal :ok value)
      (assert-equal 5 next)
      (assert-false diagnostics))))
