(in-package :cl-parser-kit/test)

(deftest-case parse-source-test
  (with-parser-tokens ("answer + 1" *identifier-plus-number-rule-specs*)
      (tokenizer tokens)
    (let ((parser (seq (type-token :identifier)
                       (type-token :plus)
                       (type-token :number))))
      (assert-parser-success (parse-tokens parser tokens)
          (value next failure)
        (assert-equal 3 next)
        (assert-equal :identifier (token-type (first value)))))))

(deftest-case parse-token-helpers-test
  (with-parser-tokens ("answer + 1" *identifier-plus-number-rule-specs*)
      (tokenizer tokens)
    (let ((parser (type-token :identifier)))
      (assert-parser-success (parse-tokens parser tokens)
          (value next failure)
        (assert-equal 1 next)))
    (let ((token (peek-token tokens 0)))
      (assert-equal :identifier (token-type token)))
    (multiple-value-bind (token next)
        (next-token tokens 0)
      (assert-equal :identifier (token-type token))
      (assert-equal 1 next))
    (assert-false (eof-token-p tokens 0))
    (assert-true (eof-token-p tokens (length tokens)))))

(deftest-case parse-failure-test
  (with-parser-tokens ("answer + 1" *identifier-plus-number-rule-specs*)
      (tokenizer tokens)
    (let ((parser (seq (type-token :identifier)
                       (type-token :plus)
                       (type-token :plus))))
      (assert-parser-failure (parse-tokens parser tokens)
          (value next failure)
        (assert-equal 2 next)
        (assert-equal :plus (parse-failure-expected failure))
        (assert-equal :number (token-type (parse-failure-actual failure)))))))

(deftest-case parse-source-success-contract-test
  (let* ((tokenizer (%make-parser-tokenizer *identifier-number-rule-specs*))
         (parser (type-token :identifier)))
    (assert-parser-success (parse-source parser "answer" tokenizer)
        (value next failure)
      (assert-equal 1 next)
      (assert-equal :identifier (token-type value)))))

(deftest-case parse-source-failure-contract-test
  (let* ((tokenizer (%make-parser-tokenizer *identifier-number-rule-specs*))
         (parser (type-token :identifier)))
    (assert-parser-failure (parse-source parser "42" tokenizer)
        (value next failure)
      (assert-equal 0 next)
      (assert-equal :identifier (parse-failure-expected failure))
      (assert-equal :number (token-type (parse-failure-actual failure))))))

(deftest-case parse-tokens-discards-success-path-diagnostics-test
    (let* ((tokens (vector (make-token :type :identifier :text "foo" :start 0 :end 3)
                         (make-token :type :comma :text "," :start 3 :end 4)))
         (parser (seq (opt (lookahead (seq (type-token :identifier)
                                           (end-of-input))))
                      (type-token :identifier)
                      (type-token :comma))))
    (assert-parser-success (parse-tokens parser tokens)
        (value next failure)
      (assert-equal 3 (length value))
      (assert-equal 2 next)
      (assert-false failure))))

(deftest-case parse-all-discards-success-path-diagnostics-test
    (let* ((tokens (vector (make-token :type :identifier :text "foo" :start 0 :end 3)
                         (make-token :type :comma :text "," :start 3 :end 4)))
         (parser (seq (opt (lookahead (seq (type-token :identifier)
                                           (end-of-input))))
                      (type-token :identifier)
                      (type-token :comma))))
    (assert-parser-success (parse-all parser tokens)
        (value next failure)
      (assert-equal 3 (length value))
      (assert-equal 2 next)
      (assert-false failure))))

(deftest-case parse-source-discards-success-path-diagnostics-test
    (let* ((tokenizer (%make-parser-tokenizer *identifier-comma-rule-specs*))
         (parser (seq (opt (lookahead (seq (type-token :identifier)
                                           (end-of-input))))
                      (type-token :identifier)
                      (type-token :comma))))
    (assert-parser-success (parse-source parser "foo," tokenizer)
        (value next failure)
      (assert-equal 3 (length value))
      (assert-equal 2 next)
      (assert-false failure))))
