(in-package :cl-parser-kit/test)

(it-sequential "pratt-public-accessor-contract-test"
  (let* ((nud #'%pratt-number-nud)
         (postfix-led #'%pratt-postfix-led)
         (infix-led #'%pratt-add-led)
         (prefix-entry (make-pratt-prefix-entry :binding-power 7 :nud nud))
         (infix-entry (make-pratt-infix-entry :left-binding-power 10
                                              :right-binding-power 11
                                              :led infix-led))
         (postfix-entry (make-pratt-postfix-entry :binding-power 20 :led postfix-led)))
    (with-pratt-number-table (table)
    (expect (typep table 'pratt-table) :to-be-truthy)
    (expect (typep prefix-entry 'pratt-prefix-entry) :to-be-truthy)
    (expect (typep infix-entry 'pratt-infix-entry) :to-be-truthy)
    (expect (typep postfix-entry 'pratt-postfix-entry) :to-be-truthy)
    (expect (hash-table-count (pratt-table-prefixes table)) :to-equal 1)
    (expect (hash-table-count (pratt-table-infixes table)) :to-equal 0)
    (expect (hash-table-count (pratt-table-postfixes table)) :to-equal 0)
    (register-prefix-operator table :number 0 nud)
    (register-infix-operator table :plus 10 11 infix-led)
    (register-postfix-operator table :bang 20 postfix-led)
    (let ((registered-prefix (gethash :number (pratt-table-prefixes table)))
          (registered-infix (gethash :plus (pratt-table-infixes table)))
          (registered-postfix (gethash :bang (pratt-table-postfixes table))))
      (expect (typep registered-prefix 'pratt-prefix-entry) :to-be-truthy)
      (expect (typep registered-infix 'pratt-infix-entry) :to-be-truthy)
      (expect (typep registered-postfix 'pratt-postfix-entry) :to-be-truthy)
    (expect (hash-table-count (pratt-table-prefixes table)) :to-equal 1)
    (expect (hash-table-count (pratt-table-infixes table)) :to-equal 1)
    (expect (hash-table-count (pratt-table-postfixes table)) :to-equal 1)))))
