(in-package :cl-parser-kit/test)

(deftest-case pratt-public-accessor-contract-test
  (let* ((nud #'%pratt-number-nud)
         (postfix-led #'%pratt-postfix-led)
         (infix-led #'%pratt-add-led)
         (prefix-entry (make-pratt-prefix-entry :binding-power 7 :nud nud))
         (infix-entry (make-pratt-infix-entry :left-binding-power 10
                                              :right-binding-power 11
                                              :led infix-led))
         (postfix-entry (make-pratt-postfix-entry :binding-power 20 :led postfix-led)))
    (with-pratt-number-table (table)
    (assert-true (typep table 'pratt-table))
    (assert-true (typep prefix-entry 'pratt-prefix-entry))
    (assert-true (typep infix-entry 'pratt-infix-entry))
    (assert-true (typep postfix-entry 'pratt-postfix-entry))
    (assert-equal 0 (hash-table-count (pratt-table-prefixes table)))
    (assert-equal 0 (hash-table-count (pratt-table-infixes table)))
    (assert-equal 0 (hash-table-count (pratt-table-postfixes table)))
    (register-prefix-operator table :number 0 nud)
    (register-infix-operator table :plus 10 11 infix-led)
    (register-postfix-operator table :bang 20 postfix-led)
    (let ((registered-prefix (gethash :number (pratt-table-prefixes table)))
          (registered-infix (gethash :plus (pratt-table-infixes table)))
          (registered-postfix (gethash :bang (pratt-table-postfixes table))))
      (assert-true (typep registered-prefix 'pratt-prefix-entry))
      (assert-true (typep registered-infix 'pratt-infix-entry))
      (assert-true (typep registered-postfix 'pratt-postfix-entry))
    (assert-equal 1 (hash-table-count (pratt-table-prefixes table)))
    (assert-equal 1 (hash-table-count (pratt-table-infixes table)))
    (assert-equal 1 (hash-table-count (pratt-table-postfixes table)))))))
