(defpackage :cl-parser-kit
  (:use :cl)
  (:export
   ;; spans
   #:span
   #:make-span
   #:span-source
   #:span-start
   #:span-end
   #:span-start-line
   #:span-start-column
   #:span-end-line
   #:span-end-column
   #:span-length
   #:span-empty-p
   #:span-merge
   ;; tokens
   #:token
   #:make-token
   #:token-type
   #:token-text
   #:token-value
   #:token-metadata
   #:token-span
   #:token-start
   #:token-end
   ;; tokenizers
   #:token-rule
   #:make-token-rule
   #:token-rule-type
   #:token-rule-matcher
   #:token-rule-skip-p
   #:tokenizer
   #:make-tokenizer
   #:tokenizer-rules
   #:tokenize
   #:tokenize-string
   #:make-literal-rule
   #:make-keyword-rule
   #:make-whitespace-rule
   #:make-identifier-rule
   #:make-number-rule
   #:make-string-rule
   #:make-predicate-rule
   #:make-line-comment-rule
   #:make-block-comment-rule
   ;; diagnostics
   #:diagnostic
   #:make-diagnostic
   #:diagnostic-kind
   #:diagnostic-message
   #:diagnostic-span
   #:diagnostic-notes
   #:diagnostic-fixes
   #:diagnostic-data
   #:diagnostic->string
   #:warning-diagnostic
   #:error-diagnostic
   #:note-diagnostic
   #:fix-it
   #:make-fix-it
   #:fix-it-span
   #:fix-it-replacement
   #:parse-failure
   #:make-parse-failure
   #:parse-failure-position
   #:parse-failure-expected
   #:parse-failure-actual
   #:parse-failure-diagnostics
   #:parse-failure-committed-p
   #:parse-failure->string
   #:merge-parse-failures
   ;; parser combinators
   #:parser
   #:make-parser
   #:parser-name
   #:parser-fn
   #:run-parser
   #:parse-source
   #:parse-tokens
   #:parse-all
   #:literal
   #:type-token
   #:literal-text
   #:literal-value
   #:type-token-text
   #:type-token-value
   #:operator-parser
   #:satisfies-token
   #:seq
   #:alt
   #:many
   #:many1
   #:chainl1
   #:chainr1
   #:sep-by
   #:sep-by1
   #:sep-end-by
   #:sep-end-by1
   #:opt
   #:label
   #:preceded-by
   #:terminated-by
   #:between
   #:delimited-sep-by
   #:delimited-sep-by1
   #:delimited-sep-end-by
   #:delimited-sep-end-by1
   #:lookahead
   #:not-followed-by
   #:map-parser
   #:bind-parser
   #:return-parser
   #:end-of-input
   #:peek-token
   #:next-token
   #:eof-token-p
   ;; pratt parsing
   #:pratt-table
   #:make-pratt-table
   #:*maximum-pratt-recursion-depth*
   #:pratt-prefix-entry
   #:pratt-infix-entry
   #:pratt-postfix-entry
   #:make-pratt-prefix-entry
   #:make-pratt-infix-entry
   #:make-pratt-postfix-entry
   #:pratt-table-prefixes
   #:pratt-table-infixes
   #:pratt-table-postfixes
   #:register-prefix-operator
   #:register-infix-operator
   #:register-postfix-operator
   #:parse-pratt
   #:parse-pratt-all
   #:parse-pratt-source
   ;; trees
   #:ast-node
   #:make-ast-node
   #:ast-node-type
   #:ast-node-value
   #:ast-node-children
   #:ast-node-span
   #:ast-node-data
   #:ast-node->sexp
   #:cst-node
   #:make-cst-node
   #:cst-node-type
   #:cst-node-value
   #:cst-node-children
   #:cst-node-span
   #:cst-node-data
   #:cst-node->sexp))
