(defpackage :cl-parser-kit
  (:use :cl)
  (:export
   ;; spans
   #:span
   #:make-span
   #:span-source
   #:span-start
   #:span-end
   #:span-start-line
   #:span-start-column
   #:span-end-line
   #:span-end-column
   #:span-length
   #:span-empty-p
   #:span-merge
   #:span-contains-position-p
   #:span-text
   ;; tokens
   #:token
   #:make-token
   #:token-type
   #:token-text
   #:token-value
   #:token-metadata
   #:token-span
   #:token-start
   #:token-end
   #:filter-tokens
   ;; tokenizers
   #:token-rule
   #:make-token-rule
   #:token-rule-type
   #:token-rule-matcher
   #:token-rule-skip-p
   #:tokenizer
   #:make-tokenizer
   #:tokenizer-rules
   #:tokenize
   #:tokenize-string
   #:make-literal-rule
   #:make-keyword-rule
   #:make-whitespace-rule
   #:make-identifier-rule
   #:make-number-rule
   #:make-string-rule
   #:make-predicate-rule
   #:make-char-rule
   #:make-line-comment-rule
   #:make-block-comment-rule
   #:make-nested-block-comment-rule
   #:make-radix-integer-rule
   #:make-float-rule
   #:make-operator-rule
   #:*maximum-number-exponent*
   #:*maximum-tokenizer-source-length*
   #:*maximum-tokenizer-tokens*
   #:*maximum-tokenizer-rules*
   #:*maximum-tokenizer-rule-alternatives*
   #:*maximum-number-lexeme-length*
   #:tokenizer-resource-limit-exceeded
   #:tokenizer-resource-limit-exceeded-kind
   #:tokenizer-resource-limit-exceeded-value
   #:tokenizer-resource-limit-exceeded-limit
   ;; diagnostics
   #:diagnostic
   #:make-diagnostic
   #:diagnostic-kind
   #:diagnostic-message
   #:diagnostic-span
   #:diagnostic-notes
   #:diagnostic-fixes
   #:diagnostic-data
   #:diagnostic->string
   #:diagnostics->string
   #:warning-diagnostic
   #:error-diagnostic
   #:note-diagnostic
   #:fix-it
   #:make-fix-it
   #:fix-it-span
   #:fix-it-replacement
   #:apply-fix-it
   #:apply-fixes
   #:parse-failure
   #:make-parse-failure
   #:parse-failure-position
   #:parse-failure-expected
   #:parse-failure-actual
   #:parse-failure-diagnostics
   #:parse-failure-committed-p
   #:parse-failure-span
   #:parse-failure->string
   #:parse-failure->diagnostics
   #:merge-parse-failures
   #:*maximum-diagnostic-line-length*
   ;; parser combinators
   #:parser
   #:make-parser
   #:parser-name
   #:parser-fn
   #:run-parser
   #:*maximum-parser-recursion-depth*
   #:parse-source
   #:parse-tokens
   #:parse-all
   #:literal
   #:type-token
   #:literal-text
   #:literal-value
   #:type-token-text
   #:type-token-value
   #:operator-parser
   #:satisfies-token
   #:seq
   #:alt
   #:many
   #:many1
   #:chainl1
   #:chainr1
   #:sep-by
   #:sep-by1
   #:sep-end-by
   #:sep-end-by1
   #:opt
   #:label
   #:context
   #:verify
   #:commit
   #:current-position
   #:preceded-by
   #:terminated-by
   #:between
   #:delimited-sep-by
   #:delimited-sep-by1
   #:delimited-sep-end-by
   #:delimited-sep-end-by1
   #:lookahead
   #:not-followed-by
   #:not-empty
   #:map-parser
   #:bind-parser
   #:return-parser
   #:end-of-input
   #:peek-token
   #:next-token
   #:eof-token-p
   ;; choice / value combinators
   #:choice
   #:option
   #:fail-parser
   #:as-value
   #:pure
   #:sequence-of
   ;; backtracking control
   #:attempt
   ;; packrat memoization
   #:memoize
   #:with-parse-memoization
   ;; permutation
   #:permute
   ;; operator-precedence expression builder
   #:make-expression-parser
   ;; repetition combinators
   #:times
   #:skip-many
   #:skip-many1
   #:fold-many
   #:fold-many1
   #:chain-postfix
   #:many-till
   #:some-till
   #:length-count
   #:chainl
   #:chainr
   ;; applicative + span combinators
   #:seq-map
   #:pick
   #:pair
   #:separated-pair
   #:spanning
   #:recognize
   ;; token-matching primitives
   #:any-token
   #:token-type-in
   #:token-type-not-in
   #:token-text-in
   #:token-text-not-in
   #:token-value-in
   #:token-value-not-in
   #:take-while
   #:take-while1
   #:skip-while
   #:satisfies-value
   ;; range repetition
   #:times-between
   #:at-least
   #:at-most
   #:end-by
   #:end-by1
   ;; symmetric delimiter
   #:surrounded-by
   ;; error recovery
   #:skip-until
   #:recover
   ;; ergonomic macros
   #:parse-let*
   #:parser-lazy
   #:defparser
   ;; pratt parsing
   #:pratt-table
   #:make-pratt-table
   #:*maximum-pratt-recursion-depth*
   #:pratt-prefix-entry
   #:pratt-infix-entry
   #:pratt-postfix-entry
   #:make-pratt-prefix-entry
   #:make-pratt-infix-entry
   #:make-pratt-postfix-entry
   #:pratt-table-prefixes
   #:pratt-table-infixes
   #:pratt-table-postfixes
   #:register-prefix-operator
   #:register-infix-operator
   #:register-postfix-operator
   #:register-atom
   #:register-prefix
   #:register-infix-left
   #:register-infix-right
   #:register-postfix
   #:register-grouping
   #:register-ternary
   #:register-infix-non-assoc
   #:parse-pratt
   #:parse-pratt-all
   #:parse-pratt-source
   ;; trees
   #:ast-node
   #:make-ast-node
   #:ast-node-type
   #:ast-node-value
   #:ast-node-children
   #:ast-node-span
   #:ast-node-data
   #:ast-node->sexp
   #:sexp->ast-node
   #:token->ast-node
   #:ast-node-of
   #:ast-node->string
   #:ast-node->dot
   #:ast-node-walk
   #:ast-node-find
   #:ast-node-map
   #:ast-node-reduce
   #:ast-node-equal
   #:ast-node-collect
   #:ast-node-count
   #:ast-node-depth
   #:cst-node
   #:make-cst-node
   #:cst-node-type
   #:cst-node-value
   #:cst-node-children
   #:cst-node-span
   #:cst-node-data
   #:cst-node->sexp
   #:sexp->cst-node
   #:token->cst-node
   #:cst-node-of
   #:cst-node->string
   #:cst-node->dot
   #:cst-node-walk
   #:cst-node-find
   #:cst-node-map
   #:cst-node-reduce
   #:cst-node-equal
   #:cst-node-collect
   #:cst-node-count
   #:cst-node-depth))
